# Deploys Plex as a Podman pod
#
# Read-only/capability/user precautions are relaxed out of convenience, but should probably be tightened.
---
- name: "Deploy mediaserver pod"
  import_role:
    name: podman
  vars:
    user: "{{service_user}}"
    group: "{{service_group}}"
    pod_name: mediaserver
    pod_create_args: "\
      -p 3005/tcp \
      -p 8324/tcp \
      -p 32400/tcp \
      -p 32469/tcp \
      -p 1900/udp \
      -p 32410/udp \
      -p 32412/udp \
      -p 32413/udp \
      -p 32414/udp"
    pod_uid: "1"
    pod_gid: "1"
    pod_containers:
      - name: plex
        image: docker.io/plexinc/pms-docker
        default_user: true
        run_args: "\
          -e ADVERTISE_IP=http://home.ijj.li:32400/ \
          -e PLEX_UID=1 \
          -e PLEX_GID=1 \
          -e TZ={{timezone}} \
          -v {{host_data_dir}}/plex:/config \
          -v {{host_media_dir}}:/data \
          -v /run/plex:/transcode"
    host_mounts:
      - "{{host_data_dir}}/plex"
      - "/run/plex"
    expose_ports:
      - 3005/tcp
      - 8324/tcp
      - 32400/tcp
      - 32469/tcp
      - 1900/udp
      - 32410/udp
      - 32412/udp
      - 32413/udp
      - 32414/udp
