---
- name: "Configure system"
  tags:
    - provision
  become: yes
  block:
    - import_tasks: "reduce_privileged_ports.yml"
    - name: "Mount storage"
      block:
        - name: "Automount the internal HDD"
          mount:
            path: /data
            src: "/dev/disk/by-uuid/{{hdd1_uuid}}"
            fstype: ext4
            state: mounted
        - name: "Install NAS client"
          apt:
            name: nfs-common
        - name: "Create NAS mountpoint"
          file:
            path: /nas
            state: directory
            group: root
        - name: "Automount the NAS 'Documents' directory"
          mount:
            path: "{{host_documents_dir}}"
            src: "{{nas_host}}:/Documents"
            fstype: nfs
            state: mounted
        - name: "Automount the NAS 'Media' directory"
          mount:
            path: "{{host_media_dir}}"
            src: "{{nas_host}}:/Media"
            fstype: nfs
            state: mounted
    - name: "Create '{{service_user}}' user for running services"
      user:
        name: "{{service_user}}"
        group: "{{service_group}}"
    - name: "Allow Podman containers to access host"
      import_role:
        name: firewall
      vars:
        ports: "{{expose_ports}}"
    - name: "Configure Wireguard"
      block:
        - import_tasks: "wireguard.yml"

- name: "Create service config and data directories"
  tags:
    - deploy
  become: yes
  file:
    path: "{{item}}"
    state: directory
    # TODO re-enable these ownerships when using rootless podman
    # owner: "{{service_user}}"
    # group: "{{service_group}}"
  loop:
    - "/data/duplicati"
    - "{{host_config_dir}}/nextcloud"
    - "{{host_config_dir}}/syncthing"
    - "{{host_data_dir}}/gitolite/git"
    - "{{host_data_dir}}/gitolite/keys"
    - "{{host_data_dir}}/nextcloud"
    - "{{host_data_dir}}/nextcloud-mariadb"
    - "{{host_data_dir}}/nextcloud-redis"
    - "{{host_data_dir}}/plex"
    - "{{host_data_dir}}/rproxy/certs"
    - "{{host_data_dir}}/rproxy/certs"
    - "{{host_data_dir}}/rproxy/logs"
    - "{{host_data_dir}}/unifi"
    # TODO use $XDG_RUNTIME_DIR instead of /run when using rootless podman
    - "/run/plex"
- name: "Configure services"
  tags:
    - deploy
    - update
  become: yes
  block:
    - import_tasks: "configure_web_service.yml"
- name: "Deploy services"
  block:
    - name: "Deploy backup service"
      block:
        - import_tasks: "deploy_web_service.yml"
    - name: "Deploy git service"
      block:
        - import_tasks: "deploy_git_service.yml"
    - name: "Deploy mediaserver service"
      block:
        - import_tasks: "deploy_mediaserver_service.yml"
    - name: "Deploy sync service"
      block:
        - import_tasks: "deploy_sync_service.yml"
    - name: "Deploy torrent service"
      block:
        - import_tasks: "deploy_torrent_service.yml"
    - name: "Deploy unifi service"
      block:
        - import_tasks: "deploy_unifi_service.yml"
    - name: "Deploy web service"
      block:
        - import_tasks: "deploy_web_service.yml"
