---
- name: Start service
  become: yes
  systemd:
    name: "{{service_name}}"
    enabled: yes
    state: started
- name: Restart service
  become: yes
  systemd:
    name: "{{service_name}}"
    state: restarted
