---
- name: Add identity key to authorized keys on host
  authorized_key: user={{ ssh_user }}
    key="{{ lookup('file', ssh_identity_key) }}"
  register: add_identity_key
  when: ssh_identity_key is defined and ssh_user is defined

- name: Create sshd_config and set permissions to root/600
  template:
    src: "opensshd.conf.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0600"
    owner: "{{ ssh_owner }}"
    group: "{{ ssh_group }}"
    validate: "/usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s"
  notify: restart sshd
  when: ssh_server_hardening | bool
