---
- name: "Create sshd_config with root/600 permissions"
  become: yes
  tags:
    - provision
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0600"
    owner: "root"
    group: "root"
    validate: "/usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s"
  notify: restart sshd
