---
- name: "Install Transmission"
  tags:
    - deploy
  become: yes
  block:
    - name: "Add Transmision apt repository"
      apt_repository:
        repo: "ppa:transmissionbt/ppa"
    - name: "Install Transmission"
      package:
        name:
          - transmission-cli
          - transmission-daemon
        state: present
    - name: "Open firewall ports for Transmission"
      import_role:
        name: firewall
      vars:
        ports:
          - "9091/tcp"
          - "51413/tcp"
          - "51413/udp"
- name: "Deploy Transmission"
  become: yes
  block:
    - name: "Stop Transmission daemon"
      tags:
        - deploy
        - stop
      systemd:
        name: "transmission-daemon"
        state: stopped
      failed_when: false
    - name: "Copy Transmission configuration file"
      tags:
        - deploy
      template:
        src: "transmission/settings.json"
        dest: "/var/lib/transmission-daemon/.config/transmission-daemon/"
    - name: "Enable Transmission daemon"
      tags:
        - deploy
      systemd:
        name: "transmission-daemon"
        enabled: yes
    - name: "Start Transmission daemon"
      tags:
        - deploy
        - start
      systemd:
        name: "transmission-daemon"
        enabled: yes
        state: started
