# Read-only/capability/user precautions are relaxed out of convenience, but should probably be tightened.
---
- name: "Deploy pod"
  import_role:
    name: podman
  vars:
    user: "{{service_user}}"
    group: "{{service_group}}"
    pod_name: web
    pod_create_args: -p 80:8080 -p 443:8443
    pod_uid: "1"
    pod_gid: "1"
    pod_containers:
      - name: rproxy
        image: docker.io/caddy
        default_user: true
        run_args: "\
          --read-only \
          --ulimit nofile=16384 \
          -v {{host_config_dir}}/rproxy/Caddyfile:/etc/caddy/Caddyfile:ro \
          -v {{host_data_dir}}/rproxy/config:/config \
          -v {{host_data_dir}}/rproxy/data:/data"
      - name: nextcloud-mariadb
        image: docker.io/mariadb
        run_args: "\
          -v {{host_data_dir}}/nextcloud-mariadb:/var/lib/mysql"
        cmd_args: "\
          --innodb-file-per-table=1\
          --transaction-isolation=READ-COMMITTED"
      - name: nextcloud-redis
        image: docker.io/redis:alpine
        run_args: "\
          --read-only \
          -v {{host_data_dir}}/nextcloud-redis:/data"
      - name: nextcloud
        image: docker.io/nextcloud:20
        default_user: true
        run_args: "\
          -e APACHE_DISABLE_REWRITE_IP=1 \
          -v {{host_config_dir}}/nextcloud:/var/www/html \
          -v {{host_data_dir}}/nextcloud:/data \
          -v {{host_documents_dir}}:/nas/documents \
          -v {{host_media_dir}}:/nas/media"
    host_mounts:
      - "{{host_config_dir}}/rproxy/Caddyfile"
      - "{{host_data_dir}}/rproxy/certs"
      - "{{host_data_dir}}/rproxy/logs"
      - "{{host_data_dir}}/nextcloud-mariadb"
      - "{{host_data_dir}}/nextcloud-redis"
    expose_ports:
      - 80/tcp
      - 443/tcp
- name: Add cron job to run Nextcloud's cron.php
  tags:
    - deploy
  become: yes
  ansible.builtin.cron:
    name: "run Nextcloud config.php"
    minute: "*/5"
    job: "podman exec -u www-data nextcloud php cron.php"
- name: Remove cron job to run Nextcloud's cron.php
  tags:
    - never
    - withdraw
  become: yes
  ansible.builtin.cron:
    name: "run Nextcloud config.php"
    state: absent
