---
- name: "Configure system"
  tags:
    - provision
  become: yes
  block:
    - name: "Set timezone"
      command: "timedatectl set-timezone {{timezone}}"
    - import_tasks: "reduce_privileged_ports.yml"
    - name: "Mount storage"
      block:
        - name: "Automount the internal HDD"
          mount:
            path: /data
            src: "/dev/disk/by-uuid/{{hdd1_uuid}}"
            fstype: ext4
            state: mounted
        - name: "Install NAS client"
          apt:
            name: nfs-common
        - name: "Create NAS mountpoint"
          file:
            path: /nas
            state: directory
            group: root
        - name: "Automount the NAS 'Documents' directory"
          mount:
            path: "{{host_documents_dir}}"
            src: "{{nas_host}}:/Documents"
            fstype: nfs
            state: mounted
        - name: "Automount the NAS 'Media' directory"
          mount:
            path: "{{host_media_dir}}"
            src: "{{nas_host}}:/Media"
            fstype: nfs
            state: mounted
    - name: "Create '{{service_user}}' user for running services"
      user:
        name: "{{service_user}}"
        group: "{{service_group}}"
    - name: "Configure Wireguard"
      block:
        - import_tasks: "wireguard.yml"
- name: "Install Prometheus Node Exporter"
  tags:
    - deploy
  import_role:
    name: prometheus_node_exporter
