- name: "Install firewalld"
  package:
    name: firewalld
    state: present
- name: "Enable and start firewalld service"
  service:
    name: firewalld
    enabled: yes
    state: started
- name: "Open firewall ports"
  firewalld:
    port: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ports}}"
