version: "3.7"

services:
  caddy:
    build: images/caddy
    container_name: caddy
    restart: unless-stopped
    user: "1000:100"
    networks:
      - caddy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - {{host_config_dir}}/caddy/Caddyfile:/etc/Caddyfile:ro
      - {{host_data_dir}}/caddy/certs:/etc/ssl/caddy
      - {{host_data_dir}}/caddy/logs:/var/log/caddy
      - {{host_data_dir}}/goaccess/report:/srv/static/stats.ijj.li:ro
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /srv/static
    cap_drop:
      - all
  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    restart: unless-stopped
    #user: "1000:100"
    networks:
      - goaccess
    command: --config-file=/srv/data/goaccess.conf
    ports:
      - "7890:7890"
    volumes:
      - {{host_config_dir}}/goaccess:/srv/data
      - {{host_data_dir}}/caddy/certs/acme/acme-v02.api.letsencrypt.org/sites/stats.ijj.li:/srv/certs:ro
      - {{host_data_dir}}/goaccess/geoip:/srv/geoip
      - {{host_data_dir}}/caddy/logs:/srv/logs
      - {{host_data_dir}}/goaccess/report:/srv/report
    read_only: true
    tmpfs:
      - /run
      - /tmp
    cap_drop:
      - all

networks:
  caddy:
  goaccess:
