---
- name: "Install Docker dependencies"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
- name: "Add Docker apt key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
- name: "Add Docker apt repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
- name: "Install Docker"
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: "Install Docker Compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: "755"
- name: "Add Ansible user to 'docker' group"
  user:
    name: "{{ansible_user}}"
    groups:
      - docker
    append: true
