---
- name: "Add Kubic apt key"
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ansible_distribution_version}}/Release.key"
- name: "Add Kubic apt repository"
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ansible_distribution_version}}/ /"
- name: "Install podman and recommended dependencies"
  apt:
    update_cache: yes
    name:
      - dnsmasq
      - fuse-overlayfs
      - podman
      - slirp4netns
