# For details about rootless Podman setup, see
# https://github.com/containers/libpod/blob/master/docs/tutorials/rootless_tutorial.md
---
- name: "Install Podman"
  become: yes
  block:
    - name: "Allow unprivileged use of ping"
      sysctl:
        name: net.ipv4.ping_group_range
        value: "0 2000000"
        sysctl_set: yes
    - name: "Install podman and recommended dependencies"
      apt:
        update_cache: yes
        name:
          - dnsmasq # For name resolution betwen containers
          - fuse-overlayfs # For volume mounting
          - slirp4netns
          - podman
          - runc
