- name: "Create config & data directories"
  become: yes
  file:
    path: "{{host_data_dir}}/plex"
    state: directory
    # TODO re-enable these ownerships when using rootless podman
    # owner: "{{service_user}}"
    # group: "{{service_group}}"
