---
- name: "Provision the host"
  become: yes
  tags:
    - provision
  block:
    - name: "Update package cache"
      apt:
        update_cache: yes
    - import_tasks: "tasks/packages/Ubuntu/docker.yml"
- name: "Copy Docker Compose config"
  tags:
    - build
    - deploy
  template:
    src: "docker-compose.yml"
    dest: "{{host_root_dir}}/"
- name: "Build service images"
  tags:
    - build
  block:
    - name: "Copy Caddy build files"
      copy:
        src: "../images/caddy"
        dest: "{{host_image_dir}}"
    - name: "Build container images"
      command: "docker-compose build"
- name: "Deploy service configuration"
  tags:
    - deploy
  block:
    - name: "Copy Caddy configuration"
      template:
        src: "Caddyfile"
        dest: "{{host_config_dir}}/caddy/"
        validate: "sudo podman run --rm -v %s:/etc/Caddyfile localhost/caddy -conf /etc/Caddyfile -validate"
    - name: "Copy GoAccess configuration"
      copy:
        src: "goaccess.conf"
        dest: "{{host_config_dir}}/goaccess/"
    - name: "Create GoAccess geoip directory"
      file:
        path: "{{host_data_dir}}/goaccess/geoip"
        state: directory
    - name: "Copy GoAccess GeoIP database"
      copy:
        src: "GeoLite2-City.mmdb"
        dest: "{{host_data_dir}}/goaccess/geoip/"
