---
# Provisions and deploys services for the ijj.li host.
#
# Tags:
#   - provision:  Provisions the host
#   - deploy:     Updates and deploys services
- name: "Provision the host"
  become: yes
  tags:
    - provision
  block:
    - import_tasks: "tasks/packages/Ubuntu/podman.yml"
- name: "Deploy Caddy container"
  tags:
    - deploy
  block:
    - name: "Create Caddy certs directory"
      file:
        path: "{{ host_data_dir }}/caddy/certs"
        state: directory
    - name: "Create Caddy logs directory"
      file:
        path: "{{ host_data_dir }}/caddy/logs"
        state: directory
    - name: "Create Caddy srv directory"
      file:
        path: "{{ host_data_dir }}/caddy/srv"
        state: directory
    - name: "Copy Caddy image"
      shell: 'podman save localhost/caddy | gzip | ssh {{ansible_user}}@{{inventory_hostname}} "gunzip | sudo podman load caddy"'
      delegate_to: localhost
    - name: "Copy Caddy configuration"
      template:
        src: "Caddyfile"
        dest: "{{ host_config_dir }}/caddy/Caddyfile"
        validate: "sudo podman run --rm -v %s:/etc/Caddyfile localhost/caddy -conf /etc/Caddyfile -validate"
