---
global:
  scrape_interval: 60s
  evaluation_interval: 60s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          class: server
  - job_name: psh-nuc-node
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          class: server
  - job_name: psh-qnap-node
    static_configs:
      - targets: ["192.168.1.20:9100"]
        labels:
          class: storage
  - job_name: ubnt
    static_configs:
      - targets: ["192.168.1.1:9100"]
        labels:
          class: router
